# Generated by Django 3.2.5 on 2021-07-26 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Category name', max_length=100, unique=True, verbose_name='category name')),
                ('description', models.CharField(help_text='Description category', max_length=255, unique=True, verbose_name='Description category')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Date time at which an object was created', verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Date time at which an object was modified', verbose_name='updated_at')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('intro', models.CharField(max_length=255, verbose_name='intro')),
                ('body', models.TextField()),
                ('image_header', models.ImageField(upload_to='posts/photos', verbose_name='image_header')),
                ('is_draft', models.BooleanField(default=True, verbose_name='is_draft')),
                ('url', models.SlugField(max_length=255, unique=True, verbose_name='url')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='published_date')),
                ('categories', models.ManyToManyField(to='blog.Category')),
            ],
            options={
                'ordering': ['-publish_date'],
                'get_latest_by': 'created_at',
                'abstract': False,
            },
        ),
    ]
